---
title: "Bigfoot Sightings"
output: html_notebook
---
load BFRO sighting report from Kaggle dataset
```{r}
library(tidyverse)
library(broom)
library(lubridate)
library(ggplot2)
library(ggmap)
#library(sp)
library(maps)
library(mapproj)
library(rgdal)
library(choroplethr)
library(choroplethrMaps)


```

```{r}
states_map<-map_data("state")
states_map_48 <- as_data_frame(map_data("state")) %>% select(-subregion)
states_map_48_nested<-states_map_48 %>% 
  ungroup() %>% 
  transmute(region=as.factor(region),
            longitude=long,
            latitude=lat)%>%
  group_by(region) %>% 
  nest()

# files from https://www.census.gov/geo/maps-data/data/cbf/cbf_counties.html put in gis directory
states_map_50<-readOGR(dsn="gis",layer="cb_2016_us_state_20m")


states_map_50_nested<-tidy(states_map_50) %>% 
  as_data_frame() %>% 
  mutate(id=as.factor(id)) %>% 
  group_by(id) %>% 
  nest() %>% 
  bind_cols(region=states_map_50$NAME) %>% 
  group_by(region)
  
states_map_50<-states_map_50_nested %>% unnest()  %>% select(id,region,long,lat)
```
```{r}

bfro_data<-read_csv("bfro-report-locations.csv")
bfro_data<-bfro_data %>% mutate(region=as.character(NA))

```


Use the point.in.poly function to assign a state to the lat/long data in data set from Kaggle.
```{r}
for (st in states_map_50_nested$region){
  poly.x<-states_map_50_nested %>% filter(region==st) %>% .$data %>% .[[1]] %>% .$long
  poly.y<-states_map_50_nested %>% filter(region==st) %>% .$data %>% .[[1]] %>% .$lat
  state_flag<-as.logical(point.in.polygon(bfro_data$longitude,bfro_data$latitude,poly.x,poly.y))
  if (TRUE %in% state_flag){
    bfro_data[as.logical(state_flag),]$region=st
  }
  
}
bfro_data<-bfro_data %>% mutate(Year=year(timestamp))
state_sum<-bfro_data %>%  mutate(region=str_to_lower(region)) %>% group_by(region) %>% summarise(value=n())
state_year_sum<-bfro_data  %>% mutate(region=str_to_lower(region)) %>% group_by(region,Year) %>% summarise(value=n())

```

```{r}
  
  getMap<-function(g,bf_data,year=0) {
    #assume any year into future is cumulative sightings for all years
    if (year==0 | year > year(Sys.Date())) {
      g<-g %+% bf_data
      title = "All Sighting Years"
      g <- g + scale_fill_distiller(name="Bigfoot\nSightings", palette="Greens", na.value="#7f7f7f")
      title<- "All Sighting Years"
    }
    else {
      g<-g %+% filter(bf_data,Year==year)
      title = paste("Sighting Year",year)
    }
    g<-g + ggtitle(title)
    g<-g + coord_map()
    return (g)
  }
  

#ggplot()+geom_map(data=states_map_48,map=states_map_48,aes(x=long,y=lat,map_id=region),color="white",fill="grey")+coord_map()

gg<-state_choropleth(state_sum,num_colors = 1)+ggtitle("All Sighting Years")
gg <- gg + scale_fill_distiller(name="Bigfoot\nSightings", palette="Greens",direction = 1)

print(gg)
```

```{r}
#set up map plot defaults
  thisYear<-year(Sys.Date())
maxSights<-max(state_sum$value)
#  gg<-ggplot(state_sum, 
#             aes(map_id =region)) + 
  gg<-ggplot() + 
    geom_map(data=states_map_48,
             map=states_map_48,
             aes(x=long,y=lat,map_id=region),
             color="white",
             fill="grey")+
    coord_map()
  #+
  #  expand_limits(x = bfro_data$longitude, y = bfro_data$latitude)
  #gg <- gg + theme_bw()
  gg <- gg + scale_fill_distiller(name="Bigfoot\nSightings", palette="Greens", na.value="#7f7f7f",limits=c(maxSights,0))
  # gg <- gg + theme(plot.title=element_text(face="bold", hjust=0, size=24))
  # gg <- gg + theme(panel.border=element_blank())
  # gg <- gg + theme(panel.grid=element_blank())
  # gg <- gg + theme(axis.ticks=element_blank())
  # gg <- gg + theme(axis.text=element_blank())
  # gg<- gg + labs(x="",y="")
  # gg <- gg + theme(strip.background=element_blank())
  #gg <- gg+borders("state")
  
print(getMap(gg,state_sum,2001))
```

```{r}
#timeline of all sightings  
startYear<-1980
#fills<-c(rep("darkgreen",inputYr-startYear-1),"blue",rep("darkgreen",thisYear-inputYr))
#subsetYear<-state_year_sum %>% filter(Year>startYear,Year<thisYear+1) %>% group_by(Year) %>% summarize(Sightings=sum(value))
p<-ggplot(data=subsetYear)
p<-p+geom_col(aes(x=Year,y=Sightings),fill="darkgreen")+ggtitle("USA Bigfoot Sightings by Year")
print(p)

```

```{r}
#timeline of all sightings highlighting particular year  
startYear<-1980
inputYr<-2001
thisYear<-year(Sys.Date())
fills<-c(rep("darkgreen",inputYr-startYear-1),"blue",rep("darkgreen",thisYear-inputYr))
subsetYear<-state_year_sum %>% filter(Year>startYear,Year<thisYear+1) %>% group_by(Year) %>% summarize(Sightings=sum(value))
p<-ggplot(data=subsetYear)
p<-p+geom_col(aes(x=Year,y=Sightings),fill=(fills))
print(p)

```
